# Generated by Django 4.2.4 on 2024-03-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictanyy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
