# Generated by Django 4.2.4 on 2024-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictanyy', '0002_alter_youtubevideo_channel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
