# Generated by Django 4.2.4 on 2024-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictanyy', '0003_alter_youtubevideo_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='channel_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
